export default {
 zhiChuFaYiCi: '只触发一次',
 changAnLe: '长按了',
 zheShiFuZhiDe: '这是复制的内容',
 fangDou: '防抖',
 changAn: '长按',
 fuZhi: '复制',
 qingPeiZhiDiTu: '请配置地图源信息',
 huHao: '胡浩',
 huoQu: '获取',
 zhiWenHuoQu: '指纹获取',
 juHeBiaoZhu: '聚合标注',
 tuoZhuaiCaoZuo: '拖拽操作',
 zhanDianCaoZuoXian: '站点操作显示',
 zhanDianHOV: '站点hover效果',
 zhanDianLianXian: '站点连线',
 tianJiaTuWenBiao: '添加图文标注',
 tianJiaWenZiBiao: '添加文字标注',
 tianJiaTuPianBiao: '添加图片标注',
 feiXingShiJiaoMan: '飞行视角-漫游',
 chuangJianXianHeQu: '创建线和区',
 jiaZaiWangLuoG: '加载网络geojson数据',
 jiaZaiBenDiG: '加载本地geojson文件',
 chuangJianGEO: '创建geojson对象数据',
 gouJianDianYaoSu: '构建点要素',
 chuCiShiYong: '初次使用',
 fuZuJian: '\n    父组件\n    ',
};
